### ISSUE TITLE
Tester feedback: logic

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AppealsMotionToReconsider#17]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `user role`
logic | The form should allow for the filer to list other parties with the same designation.  For example, if the filer was the plaintiff, the form should ask if there are other plaintiffs (and perhaps allow them to sign on to the motion).
Other information | 
Variable being sought | `user_ask_role`
Package version | `1.0`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Tester contact info | Paul Tuttle

**Comment by stevejaubz** [comment]
Question out to Paul in email re: ask if other plaintiffs want to sign off on motion
