### ISSUE TITLE
Tester feedback: other

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AppealsMotionToReconsider#19]
## What best describes you?

testing feedback form

## User feedback:  
> testing

Question id: `basic questions intro screen`

Variable being sought: `al_intro_screen`
Package version | `1.0`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Tester contact info | stevejaubz

**Comment by stevejaubz** [comment]
test closing
